//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Purpose { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> HasLogo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Title { get; set; }
        public Nullable<int> StartFinaceYer { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public string BankAndAcNo1 { get; set; }
        public string BankAndAcNo2 { get; set; }
        public string BankAndAcNo3 { get; set; }
        public Nullable<int> CurrentFinanceyear { get; set; }
    }
}
