//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public Loan()
        {
            this.LoanCollections = new HashSet<LoanCollection>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string ContactName { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public string LoanType { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string LoanStatus { get; set; }
        public Nullable<int> InstalmentPeriod { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> SanctionDate { get; set; }
        public string Source { get; set; }
        public Nullable<double> LateFee { get; set; }
        public Nullable<int> InstalmentDueDay { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<LoanCollection> LoanCollections { get; set; }
    }
}
