//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public int Id { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Qualification1 { get; set; }
        public string University { get; set; }
        public string Collage { get; set; }
        public string StudyPeriod { get; set; }
        public string MarksOrGrad { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
