//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public Tax()
        {
            this.TaxCollections = new HashSet<TaxCollection>();
            this.TaxExcludedMembers = new HashSet<TaxExcludedMember>();
        }
    
        public int Id { get; set; }
        public string TaxName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> TaxPercentBaseIncome { get; set; }
        public Nullable<int> TaxNoOfDaysIncome { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<double> ExceptedAmount { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsNameChanged { get; set; }
    
        public virtual ICollection<TaxCollection> TaxCollections { get; set; }
        public virtual ICollection<TaxExcludedMember> TaxExcludedMembers { get; set; }
    }
}
