//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblColumn
    {
        public int ColumnId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string ColumnDispName { get; set; }
        public string DataType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
